### ISSUE TITLE
点击同步后主站未创建存档

### ISSUE THREAD

**Issue by HarumiEna** [DarrenDanielDay/arcaea-toolbelt#3]
按照使用说明在Aecaea官网登录且同步后，主站并没有成功创建存档。
![image](https://github.com/DarrenDanielDay/arcaea-toolbelt/assets/98130008/42a5c8df-83e5-4e31-a2cb-e477b012d164)
![image](https://github.com/DarrenDanielDay/arcaea-toolbelt/assets/98130008/787c64e0-a69c-40e5-adb3-52a375d1ec9f)

**Comment by DarrenDanielDay** [comment]
感谢您的反馈。

由于Chromium近期的一些变动，角色数据同步功能的实现需要进行修改，目前同步角色数据的功能暂时无法正常工作，很抱歉为您带来不便。正在寻找可能的解决方案，如有相关进度则会在此issue内跟踪。

**Comment by DarrenDanielDay** [comment]
目前已改为使用`window.open`代替`<iframe>`进行跨站通信实现。使用搭档数据同步潜力值、搭档数据功能时会看到一个外部的小弹窗。
