### ISSUE TITLE
建议在世界模式计算中加入订阅Arcaea Online所带来的加成

### ISSUE THREAD

**Issue by ghost** [DarrenDanielDay/arcaea-toolbelt#8]
如题，在世界模式计算中加入订阅Arcaea Online所带来的加成（20%、25%、30%）

**Comment by DarrenDanielDay** [comment]
感谢您的反馈。已在世界模式计算器中添加选择Arcaea Online加成值的功能：
https://github.com/DarrenDanielDay/arcaea-toolbelt/commit/370d2cd18a982389d92362b7cdcaa898f0f90bd5
